  SELECT A.ID AS RECEIPT_ID,C.ID AS ACCOUNT_ID
  ,A.AMOUNT AS TOTAL_AMOUNT
  ,A.CURRENCY		
,CONVERT(VARCHAR(10),EFFECTIVE_WHEN,23) AS DATE_OF_PAYMENT
,substring(A.[EFFECTIVE_WHEN], 12, 2) AS HOUR
,substring(A.[EFFECTIVE_WHEN], 15, 2) AS MINUTE
,substring(A.[EFFECTIVE_WHEN], 18, 2) AS SECOND
,substring(C.[NOMINAL_TERM], 13, 3)  AS LOAN_PERIOD
,substring(D.[DOWN_PAYMENT_PERIOD], 13,1 )  AS DOWNPAYENT_PERIOD
,d.PRICE_UNLOCK,D.PRICE_UPFRONT	
,CONVERT(VARCHAR(10),REGISTRATION_DATE,23) AS DATE_OF_REGISTRATION
,F.NAME AS PRODUCT_NAME
,E.ID AS GROUP_ID
,G.NAME AS ORGANIZATION_NAME
		
  FROM RECEIPTS A JOIN
  payments B ON A.ID=B.RECEIPT_ID JOIN 
  accounts C ON B.ACCOUNT_ID=C.ID JOIN 
 billings D ON C.BILLING_ID=D.ID JOIN 
 groups E ON E.ID=C.GROUP_ID JOIN 
 products F ON F.ID=E.PRODUCT_ID JOIN 
 organizations G ON G.ID=C.ORGANIZATION_ID

 